[build]
  command = "npm run build"
  publish = "out"
  functions = ".netlify/functions"

[dev]
  command = "npm run dev"
  port = 3000
  publish = "out"

# Utiliser le plugin officiel Netlify pour Next.js
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Configuration de l'environnement de build
[build.environment]
  NODE_VERSION = "18.17.1"  # Version exacte de Node.js
  NPM_VERSION = "9.6.7"     # Version exacte de npm
  NEXT_TELEMETRY_DISABLED = "1"

# Variables d'environnement spécifiques à la production
[context.production.environment]
  NODE_ENV = "production"
  NEXT_TELEMETRY_DISABLED = "1"

# Configuration pour les branches de prévisualisation
[context.deploy-preview.environment]
  NODE_ENV = "development"
  NEXT_TELEMETRY_DISABLED = "1"

# Configuration pour les branches de développement
[context.branch-deploy.environment]
  NODE_ENV = "development"
  NEXT_TELEMETRY_DISABLED = "1"
